name: 'ECS Deploy Action'
description: Github action to deploy to ECS
inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Access Key
    required: true
  aws-role-to-assume:
    description: AWS Role to assume
    required: true
  aws-region:
    description: AWS Region
    required: false
    default: eu-central-1
  ecr-registry:
    description: ECS Registry that holds repository to deploy from
    required: true
  ecr-repository:
    description: ECS Repository to deploy image from
    required: true
  ecs-cluster:
    description: ECS Cluster to deploy task definition to
    required: true
  container-name:
    description: Container name to to use in task definition
    required: true
  task-definition:
    description: Name of the task definition
    required: false
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 3600
    - name: Set image tag
      run: |
        COMMIT_HASH=${{ github.event.pull_request.head.sha }}
        echo "IMAGE_TAG=${COMMIT_HASH:0:7}" >> $GITHUB_ENV
      shell: bash

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.task-definition || inputs.ecr-repository }} --query taskDefinition > task-definition.json
      shell: bash

    - name: Patch the awslogs-stream-prefix with IMAGE_TAG
      run: |
        jq ".containerDefinitions[].logConfiguration.options[\"awslogs-stream-prefix\"] = \"${{ env.IMAGE_TAG }}\"" task-definition.json > task-definition2.json
      shell: bash

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition2.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ env.IMAGE_TAG }}

    - name: Deploy Task Definition on Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        cluster: ${{ inputs.ecs-cluster }}
        count: 1
        started-by: github-actions-${{ github.actor }}
        wait-for-finish: true
